export enum DataTestId {
    card = 'card',
    loader = 'loader',
    'navigation-showcase' = 'navigation-showcase',
    'burger-showcase' = 'burger-showcase',
    'navigation-terms' = 'navigation-terms',
    'burger-terms' = 'burger-terms',
    'navigation-contract' = 'navigation-contract',
    'burger-contract' = 'burger-contract',
    'navigation-books' = 'navigation-books',
    'burger-books' = 'burger-books',
    'burger-navigation' = 'burger-navigation',
    'button-hide-reviews' = 'button-hide-reviews',
    'button-rating' = 'button-rating',
    'button-burger' = 'button-burger',
    'slide-big' = 'slide-big',
    'slide-mini' = 'slide-mini',
    'button-menu-view-window' = 'button-menu-view-window',
    'button-menu-view-list' = 'button-menu-view-list',
    'button-search-open' = 'button-search-open',
    'input-search' = 'input-search',
    'button-search-close' = 'button-search-close',
    'error' = 'error',
}
